// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/lms/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetadminRequest struct {
}

func (m *GetadminRequest) Reset()         { *m = GetadminRequest{} }
func (m *GetadminRequest) String() string { return proto.CompactTextString(m) }
func (*GetadminRequest) ProtoMessage()    {}
func (*GetadminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{0}
}
func (m *GetadminRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetadminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetadminRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetadminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetadminRequest.Merge(m, src)
}
func (m *GetadminRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetadminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetadminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetadminRequest proto.InternalMessageInfo

type GetadminResponse struct {
	Admins []*RegisterAdminRequest `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
}

func (m *GetadminResponse) Reset()         { *m = GetadminResponse{} }
func (m *GetadminResponse) String() string { return proto.CompactTextString(m) }
func (*GetadminResponse) ProtoMessage()    {}
func (*GetadminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{1}
}
func (m *GetadminResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetadminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetadminResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetadminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetadminResponse.Merge(m, src)
}
func (m *GetadminResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetadminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetadminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetadminResponse proto.InternalMessageInfo

func (m *GetadminResponse) GetAdmins() []*RegisterAdminRequest {
	if m != nil {
		return m.Admins
	}
	return nil
}

type GetLeaveStatusRequest struct {
	Studentaddress string `protobuf:"bytes,1,opt,name=studentaddress,proto3" json:"studentaddress,omitempty"`
	Leaveid        string `protobuf:"bytes,2,opt,name=leaveid,proto3" json:"leaveid,omitempty"`
}

func (m *GetLeaveStatusRequest) Reset()         { *m = GetLeaveStatusRequest{} }
func (m *GetLeaveStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeaveStatusRequest) ProtoMessage()    {}
func (*GetLeaveStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{2}
}
func (m *GetLeaveStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveStatusRequest.Merge(m, src)
}
func (m *GetLeaveStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveStatusRequest proto.InternalMessageInfo

func (m *GetLeaveStatusRequest) GetStudentaddress() string {
	if m != nil {
		return m.Studentaddress
	}
	return ""
}

func (m *GetLeaveStatusRequest) GetLeaveid() string {
	if m != nil {
		return m.Leaveid
	}
	return ""
}

type GetLeaveStatusResponse struct {
	Status *LeaveRequest `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *GetLeaveStatusResponse) Reset()         { *m = GetLeaveStatusResponse{} }
func (m *GetLeaveStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeaveStatusResponse) ProtoMessage()    {}
func (*GetLeaveStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{3}
}
func (m *GetLeaveStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetLeaveStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetLeaveStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetLeaveStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeaveStatusResponse.Merge(m, src)
}
func (m *GetLeaveStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetLeaveStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeaveStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeaveStatusResponse proto.InternalMessageInfo

func (m *GetLeaveStatusResponse) GetStatus() *LeaveRequest {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListAllTheLeavesRequest struct {
}

func (m *ListAllTheLeavesRequest) Reset()         { *m = ListAllTheLeavesRequest{} }
func (m *ListAllTheLeavesRequest) String() string { return proto.CompactTextString(m) }
func (*ListAllTheLeavesRequest) ProtoMessage()    {}
func (*ListAllTheLeavesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{4}
}
func (m *ListAllTheLeavesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListAllTheLeavesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListAllTheLeavesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListAllTheLeavesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllTheLeavesRequest.Merge(m, src)
}
func (m *ListAllTheLeavesRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListAllTheLeavesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllTheLeavesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllTheLeavesRequest proto.InternalMessageInfo

type ListAllTheLeavesResponse struct {
	Leaves []*LeaveRequest `protobuf:"bytes,1,rep,name=leaves,proto3" json:"leaves,omitempty"`
}

func (m *ListAllTheLeavesResponse) Reset()         { *m = ListAllTheLeavesResponse{} }
func (m *ListAllTheLeavesResponse) String() string { return proto.CompactTextString(m) }
func (*ListAllTheLeavesResponse) ProtoMessage()    {}
func (*ListAllTheLeavesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{5}
}
func (m *ListAllTheLeavesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListAllTheLeavesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListAllTheLeavesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListAllTheLeavesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllTheLeavesResponse.Merge(m, src)
}
func (m *ListAllTheLeavesResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListAllTheLeavesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllTheLeavesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllTheLeavesResponse proto.InternalMessageInfo

func (m *ListAllTheLeavesResponse) GetLeaves() []*LeaveRequest {
	if m != nil {
		return m.Leaves
	}
	return nil
}

type ListAllTheStudentResponse struct {
	Students []*Student `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
}

func (m *ListAllTheStudentResponse) Reset()         { *m = ListAllTheStudentResponse{} }
func (m *ListAllTheStudentResponse) String() string { return proto.CompactTextString(m) }
func (*ListAllTheStudentResponse) ProtoMessage()    {}
func (*ListAllTheStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{6}
}
func (m *ListAllTheStudentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListAllTheStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListAllTheStudentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListAllTheStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllTheStudentResponse.Merge(m, src)
}
func (m *ListAllTheStudentResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListAllTheStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllTheStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllTheStudentResponse proto.InternalMessageInfo

func (m *ListAllTheStudentResponse) GetStudents() []*Student {
	if m != nil {
		return m.Students
	}
	return nil
}

type ListAllTheStudentRequest struct {
}

func (m *ListAllTheStudentRequest) Reset()         { *m = ListAllTheStudentRequest{} }
func (m *ListAllTheStudentRequest) String() string { return proto.CompactTextString(m) }
func (*ListAllTheStudentRequest) ProtoMessage()    {}
func (*ListAllTheStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4aaac713669af5ad, []int{7}
}
func (m *ListAllTheStudentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListAllTheStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListAllTheStudentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListAllTheStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllTheStudentRequest.Merge(m, src)
}
func (m *ListAllTheStudentRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListAllTheStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllTheStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllTheStudentRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetadminRequest)(nil), "cosmos.lms.v1beta1.GetadminRequest")
	proto.RegisterType((*GetadminResponse)(nil), "cosmos.lms.v1beta1.GetadminResponse")
	proto.RegisterType((*GetLeaveStatusRequest)(nil), "cosmos.lms.v1beta1.GetLeaveStatusRequest")
	proto.RegisterType((*GetLeaveStatusResponse)(nil), "cosmos.lms.v1beta1.GetLeaveStatusResponse")
	proto.RegisterType((*ListAllTheLeavesRequest)(nil), "cosmos.lms.v1beta1.ListAllTheLeavesRequest")
	proto.RegisterType((*ListAllTheLeavesResponse)(nil), "cosmos.lms.v1beta1.ListAllTheLeavesResponse")
	proto.RegisterType((*ListAllTheStudentResponse)(nil), "cosmos.lms.v1beta1.ListAllTheStudentResponse")
	proto.RegisterType((*ListAllTheStudentRequest)(nil), "cosmos.lms.v1beta1.ListAllTheStudentRequest")
}

func init() { proto.RegisterFile("cosmos/lms/v1beta1/query.proto", fileDescriptor_4aaac713669af5ad) }

var fileDescriptor_4aaac713669af5ad = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xbf, 0x6e, 0x13, 0x41,
	0x10, 0xc6, 0x7d, 0x01, 0x4c, 0x18, 0x4b, 0x21, 0x19, 0x09, 0xb0, 0xcf, 0xe4, 0x30, 0x17, 0x12,
	0x99, 0x7f, 0x77, 0x8a, 0x29, 0xa0, 0x24, 0x34, 0x6e, 0x52, 0x5d, 0xdc, 0x40, 0x77, 0xe1, 0x46,
	0x66, 0xa5, 0xf3, 0xad, 0xe3, 0x59, 0x47, 0x4e, 0xcb, 0x03, 0x20, 0x04, 0x0d, 0xcf, 0x43, 0x45,
	0x19, 0x89, 0x86, 0x12, 0xd9, 0x3c, 0x08, 0xca, 0xde, 0x9e, 0xed, 0xd8, 0x4b, 0x70, 0xe9, 0xdd,
	0x6f, 0xbe, 0xef, 0x37, 0xe3, 0xd9, 0x03, 0xef, 0xbd, 0xe4, 0x9e, 0xe4, 0x30, 0xed, 0x71, 0x78,
	0xba, 0x7f, 0x4c, 0x2a, 0xde, 0x0f, 0x4f, 0x86, 0x34, 0x38, 0x0b, 0xfa, 0x03, 0xa9, 0x24, 0x62,
	0x7e, 0x1f, 0xa4, 0x3d, 0x0e, 0xcc, 0xbd, 0x7b, 0xbf, 0x2b, 0x65, 0x37, 0xa5, 0x30, 0xee, 0x8b,
	0x30, 0xce, 0x32, 0xa9, 0x62, 0x25, 0x64, 0xc6, 0x79, 0x85, 0x5b, 0xb7, 0x38, 0xaa, 0x51, 0x7e,
	0xe9, 0x6f, 0xc1, 0xed, 0x36, 0xa9, 0x38, 0xe9, 0x89, 0x2c, 0xa2, 0x93, 0x21, 0xb1, 0xf2, 0x3b,
	0xb0, 0x39, 0x3b, 0xe2, 0xbe, 0xcc, 0x98, 0xf0, 0x35, 0x94, 0xf5, 0x01, 0x57, 0x9d, 0xc6, 0xb5,
	0x66, 0xa5, 0xd5, 0x0c, 0x96, 0x31, 0x82, 0x88, 0xba, 0x82, 0x15, 0x0d, 0x0e, 0xe6, 0xdc, 0x22,
	0x53, 0xe7, 0xbf, 0x85, 0x3b, 0x6d, 0x52, 0x87, 0x14, 0x9f, 0xd2, 0x91, 0x8a, 0xd5, 0x90, 0x8d,
	0x00, 0xf7, 0x60, 0x83, 0xd5, 0x30, 0xa1, 0x4c, 0xc5, 0x49, 0x32, 0x20, 0xbe, 0x88, 0x70, 0x9a,
	0xb7, 0xa2, 0x85, 0x53, 0xac, 0xc2, 0xcd, 0xf4, 0xa2, 0x5a, 0x24, 0xd5, 0x35, 0x2d, 0x28, 0x7e,
	0xfa, 0x11, 0xdc, 0x5d, 0xb4, 0x36, 0xd8, 0xaf, 0xa0, 0xcc, 0xfa, 0x44, 0x7b, 0x56, 0x5a, 0x0d,
	0x1b, 0xb6, 0x2e, 0x9c, 0xe2, 0xe6, 0x7a, 0xbf, 0x06, 0xf7, 0x0e, 0x05, 0xab, 0x83, 0x34, 0xed,
	0x7c, 0x20, 0xad, 0xe0, 0xd9, 0x7c, 0xaa, 0xcb, 0x57, 0xb3, 0x40, 0x4d, 0x55, 0xcc, 0x69, 0x85,
	0xc0, 0x5c, 0xef, 0x77, 0xa0, 0x36, 0x73, 0x3d, 0xca, 0x5b, 0x9f, 0xda, 0xbe, 0x84, 0x75, 0x33,
	0x8d, 0xc2, 0xb8, 0x6e, 0x33, 0x2e, 0xca, 0xa6, 0x62, 0xdf, 0x9d, 0x67, 0x9d, 0xba, 0xea, 0xe4,
	0xd6, 0xf7, 0xeb, 0x70, 0x43, 0x6f, 0x16, 0x7e, 0x71, 0x60, 0x73, 0xb1, 0x25, 0x7c, 0x6a, 0x45,
	0xb7, 0xcf, 0xc4, 0x7d, 0xb6, 0x9a, 0x38, 0x6f, 0xc7, 0xdf, 0xf9, 0xf8, 0xf3, 0xcf, 0xd7, 0xb5,
	0x6d, 0xac, 0x87, 0x96, 0xd5, 0x34, 0xff, 0x2a, 0x7e, 0x73, 0x60, 0x6b, 0x89, 0x1d, 0xff, 0x13,
	0x74, 0xb9, 0x45, 0xf7, 0xf9, 0x8a, 0x6a, 0xc3, 0xb5, 0xa7, 0xb9, 0x1a, 0xe8, 0xd9, 0xb8, 0x8a,
	0x99, 0x8a, 0x04, 0x3f, 0x39, 0xb0, 0x71, 0x79, 0xe3, 0xf0, 0xb1, 0x2d, 0xc9, 0xba, 0xf0, 0xee,
	0x93, 0x55, 0xa4, 0x86, 0x68, 0x57, 0x13, 0x3d, 0xc0, 0xed, 0x2b, 0x88, 0x44, 0x82, 0x23, 0x58,
	0x6f, 0x93, 0xd2, 0xef, 0x0e, 0x77, 0xfe, 0x61, 0x3f, 0xff, 0xc6, 0xdd, 0x47, 0x57, 0x8b, 0x4c,
	0xfa, 0x43, 0x9d, 0x5e, 0xc7, 0x9a, 0x2d, 0x5d, 0x4b, 0xdf, 0xec, 0xfe, 0x18, 0x7b, 0xce, 0xf9,
	0xd8, 0x73, 0x7e, 0x8f, 0x3d, 0xe7, 0xf3, 0xc4, 0x2b, 0x9d, 0x4f, 0xbc, 0xd2, 0xaf, 0x89, 0x57,
	0x7a, 0x57, 0x19, 0x69, 0xb9, 0x3a, 0xeb, 0x13, 0x1f, 0x97, 0xf5, 0xd7, 0xe6, 0xc5, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xee, 0x2f, 0xa3, 0xda, 0xde, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	ListAllTheLeaves(ctx context.Context, in *ListAllTheLeavesRequest, opts ...grpc.CallOption) (*ListAllTheLeavesResponse, error)
	ListAllTheStudent(ctx context.Context, in *ListAllTheStudentRequest, opts ...grpc.CallOption) (*ListAllTheStudentResponse, error)
	GetLeaveStatus(ctx context.Context, in *GetLeaveStatusRequest, opts ...grpc.CallOption) (*GetLeaveStatusResponse, error)
	GetAdmin(ctx context.Context, in *GetadminRequest, opts ...grpc.CallOption) (*GetadminResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ListAllTheLeaves(ctx context.Context, in *ListAllTheLeavesRequest, opts ...grpc.CallOption) (*ListAllTheLeavesResponse, error) {
	out := new(ListAllTheLeavesResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.query/ListAllTheLeaves", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListAllTheStudent(ctx context.Context, in *ListAllTheStudentRequest, opts ...grpc.CallOption) (*ListAllTheStudentResponse, error) {
	out := new(ListAllTheStudentResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.query/ListAllTheStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLeaveStatus(ctx context.Context, in *GetLeaveStatusRequest, opts ...grpc.CallOption) (*GetLeaveStatusResponse, error) {
	out := new(GetLeaveStatusResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.query/GetLeaveStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAdmin(ctx context.Context, in *GetadminRequest, opts ...grpc.CallOption) (*GetadminResponse, error) {
	out := new(GetadminResponse)
	err := c.cc.Invoke(ctx, "/cosmos.lms.v1beta1.query/GetAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	ListAllTheLeaves(context.Context, *ListAllTheLeavesRequest) (*ListAllTheLeavesResponse, error)
	ListAllTheStudent(context.Context, *ListAllTheStudentRequest) (*ListAllTheStudentResponse, error)
	GetLeaveStatus(context.Context, *GetLeaveStatusRequest) (*GetLeaveStatusResponse, error)
	GetAdmin(context.Context, *GetadminRequest) (*GetadminResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ListAllTheLeaves(ctx context.Context, req *ListAllTheLeavesRequest) (*ListAllTheLeavesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllTheLeaves not implemented")
}
func (*UnimplementedQueryServer) ListAllTheStudent(ctx context.Context, req *ListAllTheStudentRequest) (*ListAllTheStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllTheStudent not implemented")
}
func (*UnimplementedQueryServer) GetLeaveStatus(ctx context.Context, req *GetLeaveStatusRequest) (*GetLeaveStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaveStatus not implemented")
}
func (*UnimplementedQueryServer) GetAdmin(ctx context.Context, req *GetadminRequest) (*GetadminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdmin not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ListAllTheLeaves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllTheLeavesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListAllTheLeaves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.query/ListAllTheLeaves",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListAllTheLeaves(ctx, req.(*ListAllTheLeavesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListAllTheStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllTheStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListAllTheStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.query/ListAllTheStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListAllTheStudent(ctx, req.(*ListAllTheStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLeaveStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaveStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLeaveStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.query/GetLeaveStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLeaveStatus(ctx, req.(*GetLeaveStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetadminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.lms.v1beta1.query/GetAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAdmin(ctx, req.(*GetadminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.lms.v1beta1.query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAllTheLeaves",
			Handler:    _Query_ListAllTheLeaves_Handler,
		},
		{
			MethodName: "ListAllTheStudent",
			Handler:    _Query_ListAllTheStudent_Handler,
		},
		{
			MethodName: "GetLeaveStatus",
			Handler:    _Query_GetLeaveStatus_Handler,
		},
		{
			MethodName: "GetAdmin",
			Handler:    _Query_GetAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/lms/v1beta1/query.proto",
}

func (m *GetadminRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetadminRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetadminRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetadminResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetadminResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetadminResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Admins) > 0 {
		for iNdEx := len(m.Admins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Admins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Leaveid) > 0 {
		i -= len(m.Leaveid)
		copy(dAtA[i:], m.Leaveid)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Leaveid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Studentaddress) > 0 {
		i -= len(m.Studentaddress)
		copy(dAtA[i:], m.Studentaddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Studentaddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetLeaveStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetLeaveStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetLeaveStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListAllTheLeavesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListAllTheLeavesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListAllTheLeavesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ListAllTheLeavesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListAllTheLeavesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListAllTheLeavesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Leaves) > 0 {
		for iNdEx := len(m.Leaves) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Leaves[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ListAllTheStudentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListAllTheStudentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListAllTheStudentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Students) > 0 {
		for iNdEx := len(m.Students) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Students[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ListAllTheStudentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListAllTheStudentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListAllTheStudentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetadminRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetadminResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Admins) > 0 {
		for _, e := range m.Admins {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *GetLeaveStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Studentaddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Leaveid)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *GetLeaveStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *ListAllTheLeavesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ListAllTheLeavesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Leaves) > 0 {
		for _, e := range m.Leaves {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *ListAllTheStudentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Students) > 0 {
		for _, e := range m.Students {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *ListAllTheStudentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetadminRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetadminRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetadminRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetadminResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetadminResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetadminResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admins = append(m.Admins, &RegisterAdminRequest{})
			if err := m.Admins[len(m.Admins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Studentaddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Studentaddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaveid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leaveid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetLeaveStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetLeaveStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetLeaveStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &LeaveRequest{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListAllTheLeavesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListAllTheLeavesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListAllTheLeavesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListAllTheLeavesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListAllTheLeavesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListAllTheLeavesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leaves", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Leaves = append(m.Leaves, &LeaveRequest{})
			if err := m.Leaves[len(m.Leaves)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListAllTheStudentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListAllTheStudentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListAllTheStudentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Students", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Students = append(m.Students, &Student{})
			if err := m.Students[len(m.Students)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListAllTheStudentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListAllTheStudentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListAllTheStudentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
